# Generated by Django 4.2.7 on 2023-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('0011', 'Type 0011'), ('1011', 'Type 1011'), ('1111', 'Type 1111'), ('1010', 'Type 1010')], max_length=4)),
                ('spend', models.PositiveSmallIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
